feat: Download only automation resources
Dynatrace/dynatrace-configuration-as-code pull request #1003
Opened 2023-05-16 08:54 UTC by warber

#### What this PR does / Why we need it:
Similar to settings and classic configs, thie PR introduces a `--only-automation` flag to specify that only automation API resources shall be downloaded by Monaco.

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

User can specify via `--only-automation` flag that only automation resources (no settings, no classic apis) schall be downloaded. Currently the feature flag `MONACO_FEAT_AUTOMATION_RESOURCES` must be set too.

2023-05-16 08:55 UTC, warber commented on cmd/monaco/download/download_configs.go
> -// shouldDownloadClassicConfigs returns true unless onlySettings or specificSchemas but no specificAPIs are defined
I've removed the comments as it became a bit awkward to update them and write a new one for shouldDownlaodAutomationResources

2023-05-16 10:48 UTC, Laubi commented on cmd/monaco/download/download_command.go
> +	cmd.Flags().BoolVar(&f.onlyAPIs, "only-apis", false, "Only download classic config objects")
I'd argue for a `Download only classic config objects`, basically, move the `Download` to the front. Same for the ones below

2023-05-16 14:34 UTC, Laubi approved these changes

2023-05-17 06:31 UTC, jskelin commented on cmd/monaco/download/download_command.go
> +	cmd.Flags().BoolVar(&f.onlyAutomation, "only-automation", false, "Download only automation API objects")
This should be under FF

2023-05-17 06:42 UTC, jskelin requested changes
This flag should be behind FF

2023-05-17 07:38 UTC, warber commented
> This flag should be behind FF

@jskelin good catch, thanks for pointing that out, I've updated the branch

2023-05-17 07:57 UTC, warber commented
closed in favor of https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1007

2023-05-17 07:57 UTC, closed without merging