Chore: Don't use "upsert" term in error messages
Dynatrace/dynatrace-configuration-as-code pull request #984
Opened 2023-05-02 13:13 UTC by warber

#### What this PR does / Why we need it:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

2023-05-03 09:04 UTC, UnseenWizzard commented on pkg/client/dtclient/client.go
> +		return DynatraceEntity{}, fmt.Errorf("failed to create dynatrace obj: %w", err)
This is a "create or update" though, unlike the Config APIs where we can differentiate between create and update and log them differently. 

"Upsert" actually reads better to me than "create/update", but I think that would be thing to log after the change

2023-05-03 09:10 UTC, UnseenWizzard commented on pkg/rest/retry.go
> +	resp, err = sendWithBody(client, path, body)
IIRC the Config Client calls to this happen after a first try failed (and a special retry case occurred)
While the Settings client goes straight to send with retry. 

Just changing this without modifying the handling for Config client errors, means we do an extra send/retry in their case right? 
I think that's visible from your change to the request_test assert as well, which expects +1 call. 

I don't think we should just do that, it kinda breaks the max retries by now always doing +1 "retry" call for Configs as they had an original API call before.

2023-05-03 09:13 UTC, UnseenWizzard commented on pkg/rest/retry.go
> +		log.Warn("Failed to get config %s with error (HTTP %d). Waiting for %s before retrying...", url, resp.StatusCode, settings.WaitTime)
nit: These are not logging the `config` but the `url` - I think logging 

> Failed to get config https://my-end.live.dynatrace.com/api/something/something/uuid ..

reads a bit strange. 

Note that the Send one you're attempting to unify with, actually logs the `objectName`- maybe that's possible here as well. Maybe both the name and API call could be helpful also

2023-05-03 09:14 UTC, UnseenWizzard requested changes
I think some of the logging changes make the log more misleading than it was before, please take a look at the comments

2023-05-03 10:58 UTC, warber commented
@UnseenWizzard I've dropped the questionable commits, pls rereview

2023-05-03 12:53 UTC, UnseenWizzard commented on pkg/client/dtclient/client.go
> +		return DynatraceEntity{}, fmt.Errorf("failed to create settings object with externalId %s (HTTP %d)!\n\tResponse was: %s", externalId, resp.StatusCode, string(resp.Body))
```suggestion
		return DynatraceEntity{}, fmt.Errorf("failed to create or update settings object with externalId %s (HTTP %d)!\n\tResponse was: %s", externalId, resp.StatusCode, string(resp.Body))
```

Shouldn't this also be create or update @warber ?

2023-05-04 07:04 UTC, UnseenWizzard approved these changes
Thanks for addressing the multiple rounds of comments! 🚀

2023-05-04 07:09 UTC, merged